version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: feast
      POSTGRES_PASSWORD: feast
      POSTGRES_DB: feast
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  airflow:
    image: apache/airflow:2.7.0-python3.9
    container_name: airflow
    depends_on:
      - postgres
      - redis
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://feast:feast@postgres:5432/feast
      AIRFLOW__CORE__FERNET_KEY: EI4XQkwh-w3yRqH98MuucttTvyni3bOfnlAZMPAyqRQ=
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    volumes:
      - ../dags:/opt/airflow/dags
    ports:
      - "8080:8080"
    command: bash -c "airflow db init &&
           airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email abdulchribati@gmail.com &&
           airflow scheduler & exec airflow webserver"

volumes:
  pgdata: